name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'  # Schedule to run every 30 minutes

jobs:
  sync:
    name: Sync with upstream
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Sync with upstream
      run: |
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push
